[package]
name = "utils"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
path-absolutize = "3.1.1"
serde = { version = "1.0.104", features = ["derive", "rc"] }
serde_json = { version = "1.0", default-features = false, features = ["alloc"] }
sha-1 = "0.10.1"
